version: '2'
services:
    access_control_mongo:
        image: mongo:4.0
        container_name: access_control_mongo
        ports:
            - '27017:27017'
        volumes:
            - datastore:/data/db

    redis:
        image: redis:latest
        container_name: access_control_redis
        ports:
            - '6379:6379'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: access_control_mssql
        ports:
            - '1433:1433'
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=yourStrong(!)Password
          - MSSQL_PID=Express
        volumes:
          - ./docker/init_sql:/opt/init_sql
        command: sh -c 'cd /opt/init_sql; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
volumes:
    datastore:
        driver: local
