version: '2'
services:
    access_control_mongo:
        image: mongo:4.0
        container_name: access_control_mongo
        ports:
            - '27017:27017'
    redis:
        image: redis:latest
        container_name: access_control_redis
        ports:
            - '6379:6379'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
